apiVersion:apps/v1
kind:Deployment
metadata:
 name:  my-website-deploy
 labels:
  app: my-website
 spec:
  replicas:2
  selector:
   matchLabels:
    app: my-website
   template:
    metadata:
     labels:
      app: my-website
    spec:
      containers:
      - name: web-container
        image: sourabhpj/my-website:latest
        ports:
        - containerPort:80